# Generated by Django 6.0.4 on 2026-04-13 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stage', models.CharField(choices=[('lead', 'Lead'), ('diagnostico', 'Diagnóstico'), ('proposta', 'Proposta'), ('negociacao', 'Negociação'), ('fechado', 'Fechado')], default='lead', max_length=20)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('ganha', 'Ganha'), ('perdida', 'Perdida')], default='aberta', max_length=20)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.company')),
            ],
        ),
    ]
